# Generated by Django 5.2 on 2025-04-12 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 200 символов', max_length=200, verbose_name='Название мероприятия')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('contact', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('location', models.CharField(help_text='Не более 400 символов', max_length=400, verbose_name='Место проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-start_at'],
            },
        ),
    ]
