# Generated by Django 5.2 on 2025-04-18 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow'),
        ('users', '0003_alter_user_options_alter_user_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='posts.Follow', through_fields=('user', 'author'), to=settings.AUTH_USER_MODEL, verbose_name='подписки'),
        ),
    ]
